#!/bin/bash

# Enable SCL Apache HTTPD server package.

source scl_source enable httpd24

# Add Listen port if defined
if [[ ! -z "$LISTEN_PORT" ]]; then
  echo "Listen $LISTEN_PORT" >> ${HOME}/httpd.conf
fi

# Ensure we run the Apache HTTPD server as process ID 1 and in foreground.
exec httpd -DFOREGROUND
